<!DOCTYPE html>
<html lang="it">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RingAnnouncer — Valerio</title>
<meta name="description" content="RingAnnouncer Valerio — eventi, gallery, video e storie dal mondo del ring.">
<style>
:root{--bg:#080a0c;--panel:#0d1013;--paper:#f3efe7;--gold:#c4933f;--gold2:#e2bd73;--white:#f6f3eb;--muted:#b8b2a7;--red:#c82031;--line:rgba(196,147,63,.34)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--white);font-family:Arial,Helvetica,sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1460px,92vw);margin:auto}.serif{font-family:Georgia,'Times New Roman',serif}.eyebrow{font-size:.72rem;text-transform:uppercase;letter-spacing:.34em;color:var(--gold);font-weight:700}.btn{display:inline-flex;align-items:center;gap:18px;padding:15px 22px;border:1px solid var(--gold);font-size:.78rem;font-weight:800;letter-spacing:.03em}.btn.gold{background:var(--gold);color:#0b0b0b}.btn.dark{background:transparent;color:white}.brand{font-family:Georgia,'Times New Roman',serif;font-size:1.55rem;letter-spacing:.02em}.brand .ring{color:var(--gold)}.brand small{display:block;font-family:Arial,sans-serif;font-size:.48rem;letter-spacing:.52em;margin-top:5px;color:white}
.topbar{position:absolute;inset:0 0 auto 0;z-index:20;height:84px;border-bottom:1px solid rgba(255,255,255,.08);display:flex;align-items:center}.topbar-inner{display:flex;align-items:center;justify-content:space-between}.navlinks{display:flex;gap:30px;font-size:.72rem;font-weight:700;align-items:center}.navlinks a:first-child{color:var(--gold)}.social-mini{display:flex;gap:16px;font-weight:900}.nav-cta{padding:14px 22px;border:1px solid var(--gold);color:var(--gold);font-size:.72rem;font-weight:800}
.hero{min-height:760px;position:relative;overflow:hidden;background:radial-gradient(circle at 68% 24%,rgba(196,147,63,.18),transparent 30%),linear-gradient(90deg,#06080a 0 38%,#11171c 60%,#090a0b 100%)}.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.82) 0 30%,rgba(0,0,0,.32) 52%,rgba(0,0,0,.15) 72%,rgba(0,0,0,.55) 100%);z-index:1}.hero.has-image{background-size:cover;background-position:center 24%}.hero-inner{min-height:760px;display:grid;grid-template-columns:42% 58%;align-items:center;position:relative;z-index:2}.hero-copy{padding-top:78px}.hero h1{font:500 clamp(4.6rem,7.3vw,8.4rem)/.82 Georgia,'Times New Roman',serif;letter-spacing:-.045em;margin:18px 0 26px}.hero h1 .gold{color:var(--gold);display:block}.hero p{font:1.18rem/1.45 Georgia,'Times New Roman',serif;max-width:420px;color:#eee8de}.hero-actions{display:flex;gap:24px;align-items:center;margin-top:34px}.play{width:48px;height:48px;border:1px solid white;border-radius:50%;display:grid;place-items:center}.hero-side{position:absolute;right:5vw;bottom:74px;text-align:right;z-index:3}.signature{font:italic 4rem Georgia,serif;color:var(--gold2);text-shadow:0 3px 20px #000}.quote{max-width:300px;font:italic 1.05rem/1.45 Georgia,serif;color:#e8e1d7}.quote strong{color:var(--gold2);font-style:normal}.hero-badge{position:absolute;right:9vw;top:120px;border-left:2px solid var(--gold);padding-left:18px;letter-spacing:.28em;line-height:1.9;color:#f0e9df;font-size:.8rem;text-transform:uppercase;z-index:3}
.stats-band{border-top:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.08);background:#0b0e11}.stats-grid{display:grid;grid-template-columns:repeat(4,1fr)}.stat{padding:24px 26px;display:grid;grid-template-columns:44px 1fr;gap:16px;align-items:center;border-right:1px solid rgba(255,255,255,.08)}.stat:last-child{border-right:0}.stat-icon{font-size:1.7rem;color:var(--gold)}.stat strong{display:block;font-size:1.45rem}.stat span{font-size:.66rem;color:#bdb7ac;text-transform:uppercase;letter-spacing:.07em}
.main-duo{padding:34px 0 26px;background:#0a0d10}.duo-grid{display:grid;grid-template-columns:44% 56%;gap:34px}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.section-head h2{margin:0;font-size:1.55rem;letter-spacing:.03em}.section-head h2:before{content:"";width:28px;height:3px;background:var(--red);display:inline-block;vertical-align:middle;margin-right:12px}.section-link{font-size:.68rem;color:#ff3651;font-weight:800}.events-list{border-top:1px solid rgba(255,255,255,.10)}.event-row{display:grid;grid-template-columns:64px 92px 1fr 24px;gap:14px;align-items:center;padding:12px 0;border-bottom:1px solid rgba(255,255,255,.10)}.date-tile{background:#15191d;text-align:center;padding:8px 4px}.date-tile strong{display:block;font-size:1.65rem}.date-tile span{font-size:.68rem;text-transform:uppercase}.event-thumb{height:64px;background:linear-gradient(135deg,#171717,#4b4b4b);overflow:hidden}.event-thumb img{width:100%;height:100%;object-fit:cover}.event-row h3{margin:0 0 5px;font-size:.88rem;text-transform:uppercase}.event-row p{margin:2px 0;color:#bbb3a8;font-size:.7rem}.arrow{color:var(--gold);font-size:1.5rem}.gallery-grid{display:grid;grid-template-columns:1.45fr .8fr .8fr;grid-template-rows:1fr 1fr;gap:8px;height:330px}.g-main{grid-row:1/3}.g-card{position:relative;background:#15191d;overflow:hidden;border:1px solid rgba(255,255,255,.10)}.g-card img{width:100%;height:100%;object-fit:cover}.g-label{position:absolute;left:14px;bottom:12px;font-size:.82rem;font-weight:800;text-transform:uppercase}.g-label span{display:block;font-size:.65rem;color:var(--gold)}.placeholder{width:100%;height:100%;display:grid;place-items:center;background:radial-gradient(circle at 50% 35%,#32363b,#121518);color:#666}
.story{margin-top:30px;min-height:360px;position:relative;overflow:hidden;border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:linear-gradient(90deg,rgba(8,10,12,.97) 0 35%,rgba(8,10,12,.58) 56%,rgba(8,10,12,.9) 100%),radial-gradient(circle at 60% 45%,#4a3a28,#15191c 48%,#080a0c 75%)}.story.has-image{background-size:cover;background-position:center}.story-copy{padding:62px 0;max-width:510px;position:relative;z-index:2}.story h2{font:500 3.2rem/.95 Georgia,'Times New Roman',serif;margin:8px 0 18px}.story h2 .gold{color:var(--gold2)}.story p{font:1rem/1.55 Georgia,serif;color:#d8d0c4}.story-tag{position:absolute;right:5vw;top:70px;color:white;letter-spacing:.35em;text-transform:uppercase;line-height:2.1;font-size:.72rem}.story-tag:before{content:"";display:block;width:58px;height:3px;background:var(--red);margin-bottom:18px}
.media{padding:48px 0;background:#0b0e11}.video-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.video{aspect-ratio:16/9;background:#000;border:1px solid rgba(255,255,255,.08)}.video iframe{width:100%;height:100%;border:0}.social-band{padding:40px 0;background:linear-gradient(90deg,#12161a,#050607);text-align:center;border-top:1px solid rgba(255,255,255,.08)}.socials{display:flex;justify-content:center;gap:18px;flex-wrap:wrap;margin-top:18px}.social{border:1px solid var(--gold);padding:9px 14px;font-size:.7rem;text-transform:uppercase;letter-spacing:.12em}.footer{padding:30px 0 40px;background:#090b0d;border-top:1px solid var(--line)}.footer-inner{display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap}.footer-links{display:flex;gap:24px;font-size:.68rem;font-weight:700}.tagline{font-size:.68rem;letter-spacing:.32em;color:#d5cec2;text-transform:uppercase}
@media(max-width:1000px){.navlinks,.social-mini{display:none}.hero-inner{grid-template-columns:1fr}.hero{min-height:700px}.hero-copy{padding:130px 0 90px}.hero-badge,.hero-side{display:none}.stats-grid{grid-template-columns:1fr 1fr}.duo-grid{grid-template-columns:1fr}.gallery-grid{height:460px}.story-tag{display:none}.video-grid{grid-template-columns:1fr}.footer-links{display:none}}@media(max-width:620px){.hero h1{font-size:4.2rem}.hero-actions{flex-wrap:wrap}.stats-grid{grid-template-columns:1fr}.event-row{grid-template-columns:58px 72px 1fr}.event-row .arrow{display:none}.gallery-grid{grid-template-columns:1fr 1fr;height:540px}.g-main{grid-column:1/3;grid-row:auto}.story h2{font-size:2.5rem}}
</style>
</head>
<body>
@php($heroUrl = $heroMedia?->file_path ? asset($heroMedia->file_path) : null)
<header id="home" class="hero {{ $heroUrl ? 'has-image' : '' }}" @if($heroUrl) style="background-image:url('{{ $heroUrl }}')" @endif>
<div class="topbar"><div class="wrap topbar-inner"><div class="brand"><span class="ring">RING</span>ANNOUNCER<small>VALERIO</small></div><div class="navlinks"><a href="#home">HOME</a><a href="#eventi">EVENTI</a><a href="#gallery">GALLERY</a><a href="#bio">BIOGRAFIA</a><a href="#media">MEDIA</a><a href="#contatti">CONTATTI</a></div><div class="social-mini">◎ f ▶</div><a class="nav-cta" href="#eventi">PROSSIMI EVENTI →</a></div></div>
<div class="wrap hero-inner"><div class="hero-copy"><div class="eyebrow">SPORT · EMOZIONI · PERSONE</div><h1>MORE<br>THAN A<span class="gold">VOICE</span></h1><p>Ogni grande evento inizia con una grande voce.</p><div class="hero-actions"><a class="btn gold" href="#eventi">SCOPRI GLI EVENTI →</a><a class="play" href="#media">▶</a><span style="font-size:.72rem;font-weight:800">GUARDA IL VIDEO</span></div></div></div>
<div class="hero-badge">same sport<br>different emotions</div><div class="hero-side"><div class="signature">Valerio</div><div class="quote">“Lo sport è disciplina, rispetto e passione.<br>Il mio compito è dare voce a tutto questo.”</div></div>
</header>

<section class="stats-band"><div class="wrap stats-grid"><div class="stat"><div class="stat-icon">▣</div><div><strong>{{ $eventCount }}+</strong><span>eventi annunciati</span></div></div><div class="stat"><div class="stat-icon">♟</div><div><strong>50+</strong><span>città in Italia ed Europa</span></div></div><div class="stat"><div class="stat-icon">♛</div><div><strong>10+</strong><span>discipline sportive</span></div></div><div class="stat"><div class="stat-icon">★</div><div><strong>UNICA</strong><span>una grande passione</span></div></div></div></section>

<section class="main-duo"><div class="wrap duo-grid"><div id="eventi"><div class="section-head"><h2>PROSSIMI EVENTI</h2><span class="section-link">VAI AL CALENDARIO →</span></div><div class="events-list">
@forelse($upcomingEvents as $event)
<div class="event-row"><div class="date-tile"><strong>{{ optional($event->event_date)->format('d') }}</strong><span>{{ strtoupper(optional($event->event_date)->translatedFormat('M')) }}</span></div><div class="event-thumb">@if($event->cover_image)<img src="{{ asset($event->cover_image) }}" alt="{{ $event->title }}">@endif</div><div><h3>{{ $event->title }}</h3><p>⌖ {{ $event->venue ?: $event->city ?: 'Location da definire' }}</p><p>◆ {{ $event->weight_category ?: 'Evento sportivo' }}</p></div><div class="arrow">›</div></div>
@empty
@foreach($recentEvents->take(4) as $event)
<div class="event-row"><div class="date-tile"><strong>{{ optional($event->event_date)->format('d') }}</strong><span>{{ strtoupper(optional($event->event_date)->translatedFormat('M')) }}</span></div><div class="event-thumb"></div><div><h3>{{ $event->title }}</h3><p>Archivio storico</p><p>{{ $event->city ?: $event->venue ?: 'RingAnnouncer' }}</p></div><div class="arrow">›</div></div>
@endforeach
@endforelse
</div></div>
<div id="gallery"><div class="section-head"><h2>GALLERY</h2><span class="section-link">VAI ALLA GALLERY →</span></div>@php($firstGallery=$galleries->first())<div class="gallery-grid"><div class="g-card g-main">@if($firstGallery?->media?->first())<img src="{{ asset($firstGallery->media->first()->file_path) }}" alt="RingAnnouncer">@else<div class="placeholder">MOMENTI INDIMENTICABILI</div>@endif<div class="g-label"><span>Gallery</span>Momenti indimenticabili</div></div>@for($i=1;$i<5;$i++)<div class="g-card">@if($firstGallery?->media?->get($i))<img src="{{ asset($firstGallery->media->get($i)->file_path) }}" alt="Gallery RingAnnouncer">@else<div class="placeholder">RING</div>@endif<div class="g-label">{{ ['Backstage','Eventi','Media','Pubblico'][$i-1] }}</div></div>@endfor</div></div></div></section>

<section id="bio" class="story {{ $heroUrl ? 'has-image' : '' }}" @if($heroUrl) style="background-image:linear-gradient(90deg,rgba(8,10,12,.97) 0 35%,rgba(8,10,12,.55) 58%,rgba(8,10,12,.86) 100%),url('{{ $heroUrl }}')" @endif><div class="wrap"><div class="story-copy"><div class="eyebrow">BIOGRAFIA</div><h2>UNA PASSIONE<br><span class="gold">SENZA CONFINI</span></h2><p>Ring announcer, presenter e speaker specializzato in eventi di boxe, kickboxing, muay thai e MMA. Professionalità, energia e rispetto per gli atleti: questo è il mio modo di vivere il ring.</p><a class="btn dark" href="#contatti">SCOPRI LA MIA STORIA →</a></div><div class="story-tag">same sport<br>different<br>emotions</div></div></section>

<section class="media" id="media"><div class="wrap"><div class="section-head"><h2>MEDIA</h2><span class="section-link">VIDEO DAL RING</span></div><div class="video-grid">@foreach($videos->take(3) as $video)<div class="video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/{{ $video->youtube_id }}" title="{{ $video->title }}" allowfullscreen></iframe></div>@endforeach</div></div></section>
<section id="contatti" class="social-band"><div class="wrap"><div class="eyebrow">SEGUIMI SUI SOCIAL</div><div class="socials">@foreach($socialLinks as $social)<a class="social" href="{{ $social->url }}" target="_blank" rel="noopener">{{ strtoupper($social->platform) }}</a>@endforeach</div></div></section>
<footer class="footer"><div class="wrap footer-inner"><div class="brand"><span class="ring">RING</span>ANNOUNCER<small>VALERIO</small></div><div class="footer-links"><a href="#home">HOME</a><a href="#eventi">EVENTI</a><a href="#gallery">GALLERY</a><a href="#bio">BIOGRAFIA</a><a href="#media">MEDIA</a><a href="#contatti">CONTATTI</a></div><div class="tagline">Passione. Ring. Persone.</div></div></footer>
</body>
</html>